/**
 * generated by Xtext 2.17.0
 */
package de.dc.javafx.xcore.lang.edit.ui.contentassist;

import de.dc.javafx.xcore.lang.edit.ui.contentassist.AbstractEmfSupportDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class EmfSupportDslProposalProvider extends AbstractEmfSupportDslProposalProvider {
}
