/**
 * generated by Xtext 2.17.0
 */
package de.dc.javafx.xcore.lang.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.dc.javafx.xcore.lang.JavaFXDslRuntimeModule;
import de.dc.javafx.xcore.lang.JavaFXDslStandaloneSetup;
import de.dc.javafx.xcore.lang.ide.JavaFXDslIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class JavaFXDslIdeSetup extends JavaFXDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    JavaFXDslRuntimeModule _javaFXDslRuntimeModule = new JavaFXDslRuntimeModule();
    JavaFXDslIdeModule _javaFXDslIdeModule = new JavaFXDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_javaFXDslRuntimeModule, _javaFXDslIdeModule));
  }
}
