/*
 * generated by Xtext 2.14.0
 */
package de.dc.emf.javafx.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class JavaFXLangRuntimeModule extends AbstractJavaFXLangRuntimeModule {
}
