/**
 * generated by Xtext 2.17.0
 */
package de.dc.javafx.xcore.lang;

import de.dc.javafx.xcore.lang.AbstractJavaFXDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class JavaFXDslRuntimeModule extends AbstractJavaFXDslRuntimeModule {
}
