/*
 * generated by Xtext 2.14.0
 */
package de.dc.emf.javafx.xtext.jvm.lang.ide


/**
 * Use this class to register ide components.
 */
class JavaFXCuDslIdeModule extends AbstractJavaFXCuDslIdeModule {
}
