/*
 * generated by Xtext 2.14.0
 */
package de.dc.emf.javafx.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class JavaFXLangGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ProjectFXElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dc.emf.javafx.xtext.JavaFXLang.ProjectFX");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cProjectFXAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cProjectFXKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cPackagePathKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cPackagePathAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cPackagePathEStringParserRuleCall_4_1_0 = (RuleCall)cPackagePathAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cControlsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cControlsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cControlsControlFXParserRuleCall_5_2_0 = (RuleCall)cControlsAssignment_5_2.eContents().get(0);
		private final Assignment cControlsAssignment_5_3 = (Assignment)cGroup_5.eContents().get(3);
		private final RuleCall cControlsControlFXParserRuleCall_5_3_0 = (RuleCall)cControlsAssignment_5_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cModelsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cModelsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cModelsModelFXParserRuleCall_6_2_0 = (RuleCall)cModelsAssignment_6_2.eContents().get(0);
		private final Assignment cModelsAssignment_6_3 = (Assignment)cGroup_6.eContents().get(3);
		private final RuleCall cModelsModelFXParserRuleCall_6_3_0 = (RuleCall)cModelsAssignment_6_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cBindingsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cBindingsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cBindingsBindingParserRuleCall_7_2_0 = (RuleCall)cBindingsAssignment_7_2.eContents().get(0);
		private final Assignment cBindingsAssignment_7_3 = (Assignment)cGroup_7.eContents().get(3);
		private final RuleCall cBindingsBindingParserRuleCall_7_3_0 = (RuleCall)cBindingsAssignment_7_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//ProjectFX:
		//	{ProjectFX}
		//	'ProjectFX'
		//	name=EString
		//	'{' ('packagePath' packagePath=EString)? ('controls' '{' controls+=ControlFX controls+=ControlFX* '}')? ('models' '{'
		//	models+=ModelFX models+=ModelFX* '}')? ('bindings' '{' bindings+=Binding bindings+=Binding* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ProjectFX} 'ProjectFX' name=EString '{' ('packagePath' packagePath=EString)? ('controls' '{' controls+=ControlFX
		//controls+=ControlFX* '}')? ('models' '{' models+=ModelFX models+=ModelFX* '}')? ('bindings' '{' bindings+=Binding
		//bindings+=Binding* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{ProjectFX}
		public Action getProjectFXAction_0() { return cProjectFXAction_0; }
		
		//'ProjectFX'
		public Keyword getProjectFXKeyword_1() { return cProjectFXKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('packagePath' packagePath=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'packagePath'
		public Keyword getPackagePathKeyword_4_0() { return cPackagePathKeyword_4_0; }
		
		//packagePath=EString
		public Assignment getPackagePathAssignment_4_1() { return cPackagePathAssignment_4_1; }
		
		//EString
		public RuleCall getPackagePathEStringParserRuleCall_4_1_0() { return cPackagePathEStringParserRuleCall_4_1_0; }
		
		//('controls' '{' controls+=ControlFX controls+=ControlFX* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'controls'
		public Keyword getControlsKeyword_5_0() { return cControlsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//controls+=ControlFX
		public Assignment getControlsAssignment_5_2() { return cControlsAssignment_5_2; }
		
		//ControlFX
		public RuleCall getControlsControlFXParserRuleCall_5_2_0() { return cControlsControlFXParserRuleCall_5_2_0; }
		
		//controls+=ControlFX*
		public Assignment getControlsAssignment_5_3() { return cControlsAssignment_5_3; }
		
		//ControlFX
		public RuleCall getControlsControlFXParserRuleCall_5_3_0() { return cControlsControlFXParserRuleCall_5_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//('models' '{' models+=ModelFX models+=ModelFX* '}')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'models'
		public Keyword getModelsKeyword_6_0() { return cModelsKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//models+=ModelFX
		public Assignment getModelsAssignment_6_2() { return cModelsAssignment_6_2; }
		
		//ModelFX
		public RuleCall getModelsModelFXParserRuleCall_6_2_0() { return cModelsModelFXParserRuleCall_6_2_0; }
		
		//models+=ModelFX*
		public Assignment getModelsAssignment_6_3() { return cModelsAssignment_6_3; }
		
		//ModelFX
		public RuleCall getModelsModelFXParserRuleCall_6_3_0() { return cModelsModelFXParserRuleCall_6_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//('bindings' '{' bindings+=Binding bindings+=Binding* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'bindings'
		public Keyword getBindingsKeyword_7_0() { return cBindingsKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//bindings+=Binding
		public Assignment getBindingsAssignment_7_2() { return cBindingsAssignment_7_2; }
		
		//Binding
		public RuleCall getBindingsBindingParserRuleCall_7_2_0() { return cBindingsBindingParserRuleCall_7_2_0; }
		
		//bindings+=Binding*
		public Assignment getBindingsAssignment_7_3() { return cBindingsAssignment_7_3; }
		
		//Binding
		public RuleCall getBindingsBindingParserRuleCall_7_3_0() { return cBindingsBindingParserRuleCall_7_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class BindingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dc.emf.javafx.xtext.JavaFXLang.Binding");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBindingAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBindingKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Assignment cPropertyAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final RuleCall cPropertyBindingPropertyParserRuleCall_4_0_0 = (RuleCall)cPropertyAssignment_4_0.eContents().get(0);
		private final Assignment cPropertyAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cPropertyBindingPropertyParserRuleCall_4_1_0 = (RuleCall)cPropertyAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Binding:
		//	{Binding}
		//	'binding' name=EString '{' (property+=BindingProperty property+=BindingProperty*)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Binding} 'binding' name=EString '{' (property+=BindingProperty property+=BindingProperty*)? '}'
		public Group getGroup() { return cGroup; }
		
		//{Binding}
		public Action getBindingAction_0() { return cBindingAction_0; }
		
		//'binding'
		public Keyword getBindingKeyword_1() { return cBindingKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//(property+=BindingProperty property+=BindingProperty*)?
		public Group getGroup_4() { return cGroup_4; }
		
		//property+=BindingProperty
		public Assignment getPropertyAssignment_4_0() { return cPropertyAssignment_4_0; }
		
		//BindingProperty
		public RuleCall getPropertyBindingPropertyParserRuleCall_4_0_0() { return cPropertyBindingPropertyParserRuleCall_4_0_0; }
		
		//property+=BindingProperty*
		public Assignment getPropertyAssignment_4_1() { return cPropertyAssignment_4_1; }
		
		//BindingProperty
		public RuleCall getPropertyBindingPropertyParserRuleCall_4_1_0() { return cPropertyBindingPropertyParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class BindingPropertyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dc.emf.javafx.xtext.JavaFXLang.BindingProperty");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBindingPropertyAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeBindinTypeEnumRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//BindingProperty:
		//	{BindingProperty} type=BindinType name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{BindingProperty} type=BindinType name=EString
		public Group getGroup() { return cGroup; }
		
		//{BindingProperty}
		public Action getBindingPropertyAction_0() { return cBindingPropertyAction_0; }
		
		//type=BindinType
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//BindinType
		public RuleCall getTypeBindinTypeEnumRuleCall_1_0() { return cTypeBindinTypeEnumRuleCall_1_0; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class ControlFXElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dc.emf.javafx.xtext.JavaFXLang.ControlFX");
		private final RuleCall cTableViewFXParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//ControlFX:
		//	TableViewFX;
		@Override public ParserRule getRule() { return rule; }
		
		//TableViewFX
		public RuleCall getTableViewFXParserRuleCall() { return cTableViewFXParserRuleCall; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dc.emf.javafx.xtext.JavaFXLang.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class ModelFXElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dc.emf.javafx.xtext.JavaFXLang.ModelFX");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cDerivedBeanParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBeanParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//ModelFX:
		//	DerivedBean | Bean;
		@Override public ParserRule getRule() { return rule; }
		
		//DerivedBean | Bean
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//DerivedBean
		public RuleCall getDerivedBeanParserRuleCall_0() { return cDerivedBeanParserRuleCall_0; }
		
		//Bean
		public RuleCall getBeanParserRuleCall_1() { return cBeanParserRuleCall_1; }
	}
	public class DerivedBeanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dc.emf.javafx.xtext.JavaFXLang.DerivedBean");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDerivedBeanAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cClassKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cInstanceTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cInstanceTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cInstanceTypeEStringParserRuleCall_4_1_0 = (RuleCall)cInstanceTypeAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Assignment cAttributesAssignment_5_0 = (Assignment)cGroup_5.eContents().get(0);
		private final RuleCall cAttributesAttributeFXParserRuleCall_5_0_0 = (RuleCall)cAttributesAssignment_5_0.eContents().get(0);
		private final Assignment cAttributesAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cAttributesAttributeFXParserRuleCall_5_1_0 = (RuleCall)cAttributesAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//DerivedBean:
		//	{DerivedBean}
		//	'class' name=EString '{' ('instanceType:' instanceType=EString) (attributes+=AttributeFX attributes+=AttributeFX*)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{DerivedBean} 'class' name=EString '{' ('instanceType:' instanceType=EString) (attributes+=AttributeFX
		//attributes+=AttributeFX*)? '}'
		public Group getGroup() { return cGroup; }
		
		//{DerivedBean}
		public Action getDerivedBeanAction_0() { return cDerivedBeanAction_0; }
		
		//'class'
		public Keyword getClassKeyword_1() { return cClassKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//'instanceType:' instanceType=EString
		public Group getGroup_4() { return cGroup_4; }
		
		//'instanceType:'
		public Keyword getInstanceTypeKeyword_4_0() { return cInstanceTypeKeyword_4_0; }
		
		//instanceType=EString
		public Assignment getInstanceTypeAssignment_4_1() { return cInstanceTypeAssignment_4_1; }
		
		//EString
		public RuleCall getInstanceTypeEStringParserRuleCall_4_1_0() { return cInstanceTypeEStringParserRuleCall_4_1_0; }
		
		//(attributes+=AttributeFX attributes+=AttributeFX*)?
		public Group getGroup_5() { return cGroup_5; }
		
		//attributes+=AttributeFX
		public Assignment getAttributesAssignment_5_0() { return cAttributesAssignment_5_0; }
		
		//AttributeFX
		public RuleCall getAttributesAttributeFXParserRuleCall_5_0_0() { return cAttributesAttributeFXParserRuleCall_5_0_0; }
		
		//attributes+=AttributeFX*
		public Assignment getAttributesAssignment_5_1() { return cAttributesAssignment_5_1; }
		
		//AttributeFX
		public RuleCall getAttributesAttributeFXParserRuleCall_5_1_0() { return cAttributesAttributeFXParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class BeanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dc.emf.javafx.xtext.JavaFXLang.Bean");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBeanAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cClassKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Assignment cAttributesAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final RuleCall cAttributesAttributeFXParserRuleCall_4_0_0 = (RuleCall)cAttributesAssignment_4_0.eContents().get(0);
		private final Assignment cAttributesAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAttributesAttributeFXParserRuleCall_4_1_0 = (RuleCall)cAttributesAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Bean:
		//	{Bean}
		//	'class' name=EString '{' (attributes+=AttributeFX attributes+=AttributeFX*)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Bean} 'class' name=EString '{' (attributes+=AttributeFX attributes+=AttributeFX*)? '}'
		public Group getGroup() { return cGroup; }
		
		//{Bean}
		public Action getBeanAction_0() { return cBeanAction_0; }
		
		//'class'
		public Keyword getClassKeyword_1() { return cClassKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//(attributes+=AttributeFX attributes+=AttributeFX*)?
		public Group getGroup_4() { return cGroup_4; }
		
		//attributes+=AttributeFX
		public Assignment getAttributesAssignment_4_0() { return cAttributesAssignment_4_0; }
		
		//AttributeFX
		public RuleCall getAttributesAttributeFXParserRuleCall_4_0_0() { return cAttributesAttributeFXParserRuleCall_4_0_0; }
		
		//attributes+=AttributeFX*
		public Assignment getAttributesAssignment_4_1() { return cAttributesAssignment_4_1; }
		
		//AttributeFX
		public RuleCall getAttributesAttributeFXParserRuleCall_4_1_0() { return cAttributesAttributeFXParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class TableViewFXElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dc.emf.javafx.xtext.JavaFXLang.TableViewFX");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTableViewFXAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTableViewKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_3_1_0 = (RuleCall)cNameAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cUsedModelKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cUsedModelAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cUsedModelModelFXCrossReference_4_1_0 = (CrossReference)cUsedModelAssignment_4_1.eContents().get(0);
		private final RuleCall cUsedModelModelFXEStringParserRuleCall_4_1_0_1 = (RuleCall)cUsedModelModelFXCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cUsedFilterKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cUseFilterAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cUseFilterEBooleanParserRuleCall_5_1_0 = (RuleCall)cUseFilterAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Assignment cColumnsAssignment_6_0 = (Assignment)cGroup_6.eContents().get(0);
		private final RuleCall cColumnsTableColumnFXParserRuleCall_6_0_0 = (RuleCall)cColumnsAssignment_6_0.eContents().get(0);
		private final Assignment cColumnsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cColumnsTableColumnFXParserRuleCall_6_1_0 = (RuleCall)cColumnsAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//TableViewFX:
		//	{TableViewFX}
		//	'TableView' '{' ('name:' name=EString) ('usedModel:' usedModel=[ModelFX|EString])? ('usedFilter:'
		//	useFilter=EBoolean)? (columns+=TableColumnFX columns+=TableColumnFX*)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{TableViewFX} 'TableView' '{' ('name:' name=EString) ('usedModel:' usedModel=[ModelFX|EString])? ('usedFilter:'
		//useFilter=EBoolean)? (columns+=TableColumnFX columns+=TableColumnFX*)? '}'
		public Group getGroup() { return cGroup; }
		
		//{TableViewFX}
		public Action getTableViewFXAction_0() { return cTableViewFXAction_0; }
		
		//'TableView'
		public Keyword getTableViewKeyword_1() { return cTableViewKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'name:' name=EString
		public Group getGroup_3() { return cGroup_3; }
		
		//'name:'
		public Keyword getNameKeyword_3_0() { return cNameKeyword_3_0; }
		
		//name=EString
		public Assignment getNameAssignment_3_1() { return cNameAssignment_3_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_1_0() { return cNameEStringParserRuleCall_3_1_0; }
		
		//('usedModel:' usedModel=[ModelFX|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'usedModel:'
		public Keyword getUsedModelKeyword_4_0() { return cUsedModelKeyword_4_0; }
		
		//usedModel=[ModelFX|EString]
		public Assignment getUsedModelAssignment_4_1() { return cUsedModelAssignment_4_1; }
		
		//[ModelFX|EString]
		public CrossReference getUsedModelModelFXCrossReference_4_1_0() { return cUsedModelModelFXCrossReference_4_1_0; }
		
		//EString
		public RuleCall getUsedModelModelFXEStringParserRuleCall_4_1_0_1() { return cUsedModelModelFXEStringParserRuleCall_4_1_0_1; }
		
		//('usedFilter:' useFilter=EBoolean)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'usedFilter:'
		public Keyword getUsedFilterKeyword_5_0() { return cUsedFilterKeyword_5_0; }
		
		//useFilter=EBoolean
		public Assignment getUseFilterAssignment_5_1() { return cUseFilterAssignment_5_1; }
		
		//EBoolean
		public RuleCall getUseFilterEBooleanParserRuleCall_5_1_0() { return cUseFilterEBooleanParserRuleCall_5_1_0; }
		
		//(columns+=TableColumnFX columns+=TableColumnFX*)?
		public Group getGroup_6() { return cGroup_6; }
		
		//columns+=TableColumnFX
		public Assignment getColumnsAssignment_6_0() { return cColumnsAssignment_6_0; }
		
		//TableColumnFX
		public RuleCall getColumnsTableColumnFXParserRuleCall_6_0_0() { return cColumnsTableColumnFXParserRuleCall_6_0_0; }
		
		//columns+=TableColumnFX*
		public Assignment getColumnsAssignment_6_1() { return cColumnsAssignment_6_1; }
		
		//TableColumnFX
		public RuleCall getColumnsTableColumnFXParserRuleCall_6_1_0() { return cColumnsTableColumnFXParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class TableColumnFXElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dc.emf.javafx.xtext.JavaFXLang.TableColumnFX");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTableColumnFXAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cColumnKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_3_1_0 = (RuleCall)cNameAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cWidthKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cWidthAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cWidthEIntParserRuleCall_4_1_0 = (RuleCall)cWidthAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAttributeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cUsedAttributeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cUsedAttributeAttributeFXCrossReference_5_1_0 = (CrossReference)cUsedAttributeAssignment_5_1.eContents().get(0);
		private final RuleCall cUsedAttributeAttributeFXEStringParserRuleCall_5_1_0_1 = (RuleCall)cUsedAttributeAttributeFXCrossReference_5_1_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cUseFilterKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cUseFilterAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cUseFilterEBooleanParserRuleCall_6_1_0 = (RuleCall)cUseFilterAssignment_6_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//TableColumnFX:
		//	{TableColumnFX}
		//	'Column'
		//	'(' ('name:' name=EString) ('width:' width=EInt)? ('attribute:' usedAttribute=[AttributeFX|EString])? ('useFilter:'
		//	useFilter=EBoolean)?
		//	')';
		@Override public ParserRule getRule() { return rule; }
		
		//{TableColumnFX} 'Column' '(' ('name:' name=EString) ('width:' width=EInt)? ('attribute:'
		//usedAttribute=[AttributeFX|EString])? ('useFilter:' useFilter=EBoolean)? ')'
		public Group getGroup() { return cGroup; }
		
		//{TableColumnFX}
		public Action getTableColumnFXAction_0() { return cTableColumnFXAction_0; }
		
		//'Column'
		public Keyword getColumnKeyword_1() { return cColumnKeyword_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//'name:' name=EString
		public Group getGroup_3() { return cGroup_3; }
		
		//'name:'
		public Keyword getNameKeyword_3_0() { return cNameKeyword_3_0; }
		
		//name=EString
		public Assignment getNameAssignment_3_1() { return cNameAssignment_3_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_1_0() { return cNameEStringParserRuleCall_3_1_0; }
		
		//('width:' width=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'width:'
		public Keyword getWidthKeyword_4_0() { return cWidthKeyword_4_0; }
		
		//width=EInt
		public Assignment getWidthAssignment_4_1() { return cWidthAssignment_4_1; }
		
		//EInt
		public RuleCall getWidthEIntParserRuleCall_4_1_0() { return cWidthEIntParserRuleCall_4_1_0; }
		
		//('attribute:' usedAttribute=[AttributeFX|EString])?
		public Group getGroup_5() { return cGroup_5; }
		
		//'attribute:'
		public Keyword getAttributeKeyword_5_0() { return cAttributeKeyword_5_0; }
		
		//usedAttribute=[AttributeFX|EString]
		public Assignment getUsedAttributeAssignment_5_1() { return cUsedAttributeAssignment_5_1; }
		
		//[AttributeFX|EString]
		public CrossReference getUsedAttributeAttributeFXCrossReference_5_1_0() { return cUsedAttributeAttributeFXCrossReference_5_1_0; }
		
		//EString
		public RuleCall getUsedAttributeAttributeFXEStringParserRuleCall_5_1_0_1() { return cUsedAttributeAttributeFXEStringParserRuleCall_5_1_0_1; }
		
		//('useFilter:' useFilter=EBoolean)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'useFilter:'
		public Keyword getUseFilterKeyword_6_0() { return cUseFilterKeyword_6_0; }
		
		//useFilter=EBoolean
		public Assignment getUseFilterAssignment_6_1() { return cUseFilterAssignment_6_1; }
		
		//EBoolean
		public RuleCall getUseFilterEBooleanParserRuleCall_6_1_0() { return cUseFilterEBooleanParserRuleCall_6_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7() { return cRightParenthesisKeyword_7; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dc.emf.javafx.xtext.JavaFXLang.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dc.emf.javafx.xtext.JavaFXLang.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class AttributeFXElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dc.emf.javafx.xtext.JavaFXLang.AttributeFX");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAttributeFXAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//AttributeFX:
		//	{AttributeFX} type=EString name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{AttributeFX} type=EString name=EString
		public Group getGroup() { return cGroup; }
		
		//{AttributeFX}
		public Action getAttributeFXAction_0() { return cAttributeFXAction_0; }
		
		//type=EString
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//EString
		public RuleCall getTypeEStringParserRuleCall_1_0() { return cTypeEStringParserRuleCall_1_0; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	
	public class BindinTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "de.dc.emf.javafx.xtext.JavaFXLang.BindinType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cBooleanPropertyEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cBooleanPropertyBooleanPropertyKeyword_0_0 = (Keyword)cBooleanPropertyEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cDoublePropertyEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cDoublePropertyDoublePropertyKeyword_1_0 = (Keyword)cDoublePropertyEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cFloatPropertyEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cFloatPropertyFloatPropertyKeyword_2_0 = (Keyword)cFloatPropertyEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cIntegerPropertyEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cIntegerPropertyIntegerPropertyKeyword_3_0 = (Keyword)cIntegerPropertyEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cObservableListEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cObservableListObservableListKeyword_4_0 = (Keyword)cObservableListEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cObjectPropertyEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cObjectPropertyObjectPropertyKeyword_5_0 = (Keyword)cObjectPropertyEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cStringPropertyEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cStringPropertyStringPropertyKeyword_6_0 = (Keyword)cStringPropertyEnumLiteralDeclaration_6.eContents().get(0);
		
		//enum BindinType returns BindingType:
		//	BooleanProperty | DoubleProperty | FloatProperty | IntegerProperty | ObservableList | ObjectProperty |
		//	StringProperty;
		public EnumRule getRule() { return rule; }
		
		//BooleanProperty | DoubleProperty | FloatProperty | IntegerProperty | ObservableList | ObjectProperty | StringProperty
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//BooleanProperty
		public EnumLiteralDeclaration getBooleanPropertyEnumLiteralDeclaration_0() { return cBooleanPropertyEnumLiteralDeclaration_0; }
		
		//"BooleanProperty"
		public Keyword getBooleanPropertyBooleanPropertyKeyword_0_0() { return cBooleanPropertyBooleanPropertyKeyword_0_0; }
		
		//DoubleProperty
		public EnumLiteralDeclaration getDoublePropertyEnumLiteralDeclaration_1() { return cDoublePropertyEnumLiteralDeclaration_1; }
		
		//"DoubleProperty"
		public Keyword getDoublePropertyDoublePropertyKeyword_1_0() { return cDoublePropertyDoublePropertyKeyword_1_0; }
		
		//FloatProperty
		public EnumLiteralDeclaration getFloatPropertyEnumLiteralDeclaration_2() { return cFloatPropertyEnumLiteralDeclaration_2; }
		
		//"FloatProperty"
		public Keyword getFloatPropertyFloatPropertyKeyword_2_0() { return cFloatPropertyFloatPropertyKeyword_2_0; }
		
		//IntegerProperty
		public EnumLiteralDeclaration getIntegerPropertyEnumLiteralDeclaration_3() { return cIntegerPropertyEnumLiteralDeclaration_3; }
		
		//"IntegerProperty"
		public Keyword getIntegerPropertyIntegerPropertyKeyword_3_0() { return cIntegerPropertyIntegerPropertyKeyword_3_0; }
		
		//ObservableList
		public EnumLiteralDeclaration getObservableListEnumLiteralDeclaration_4() { return cObservableListEnumLiteralDeclaration_4; }
		
		//"ObservableList"
		public Keyword getObservableListObservableListKeyword_4_0() { return cObservableListObservableListKeyword_4_0; }
		
		//ObjectProperty
		public EnumLiteralDeclaration getObjectPropertyEnumLiteralDeclaration_5() { return cObjectPropertyEnumLiteralDeclaration_5; }
		
		//"ObjectProperty"
		public Keyword getObjectPropertyObjectPropertyKeyword_5_0() { return cObjectPropertyObjectPropertyKeyword_5_0; }
		
		//StringProperty
		public EnumLiteralDeclaration getStringPropertyEnumLiteralDeclaration_6() { return cStringPropertyEnumLiteralDeclaration_6; }
		
		//"StringProperty"
		public Keyword getStringPropertyStringPropertyKeyword_6_0() { return cStringPropertyStringPropertyKeyword_6_0; }
	}
	
	private final ProjectFXElements pProjectFX;
	private final BindingElements pBinding;
	private final BindingPropertyElements pBindingProperty;
	private final BindinTypeElements eBindinType;
	private final ControlFXElements pControlFX;
	private final EStringElements pEString;
	private final ModelFXElements pModelFX;
	private final DerivedBeanElements pDerivedBean;
	private final BeanElements pBean;
	private final TableViewFXElements pTableViewFX;
	private final TableColumnFXElements pTableColumnFX;
	private final EBooleanElements pEBoolean;
	private final EIntElements pEInt;
	private final AttributeFXElements pAttributeFX;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public JavaFXLangGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProjectFX = new ProjectFXElements();
		this.pBinding = new BindingElements();
		this.pBindingProperty = new BindingPropertyElements();
		this.eBindinType = new BindinTypeElements();
		this.pControlFX = new ControlFXElements();
		this.pEString = new EStringElements();
		this.pModelFX = new ModelFXElements();
		this.pDerivedBean = new DerivedBeanElements();
		this.pBean = new BeanElements();
		this.pTableViewFX = new TableViewFXElements();
		this.pTableColumnFX = new TableColumnFXElements();
		this.pEBoolean = new EBooleanElements();
		this.pEInt = new EIntElements();
		this.pAttributeFX = new AttributeFXElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.dc.emf.javafx.xtext.JavaFXLang".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//ProjectFX:
	//	{ProjectFX}
	//	'ProjectFX'
	//	name=EString
	//	'{' ('packagePath' packagePath=EString)? ('controls' '{' controls+=ControlFX controls+=ControlFX* '}')? ('models' '{'
	//	models+=ModelFX models+=ModelFX* '}')? ('bindings' '{' bindings+=Binding bindings+=Binding* '}')?
	//	'}';
	public ProjectFXElements getProjectFXAccess() {
		return pProjectFX;
	}
	
	public ParserRule getProjectFXRule() {
		return getProjectFXAccess().getRule();
	}
	
	//Binding:
	//	{Binding}
	//	'binding' name=EString '{' (property+=BindingProperty property+=BindingProperty*)?
	//	'}';
	public BindingElements getBindingAccess() {
		return pBinding;
	}
	
	public ParserRule getBindingRule() {
		return getBindingAccess().getRule();
	}
	
	//BindingProperty:
	//	{BindingProperty} type=BindinType name=EString;
	public BindingPropertyElements getBindingPropertyAccess() {
		return pBindingProperty;
	}
	
	public ParserRule getBindingPropertyRule() {
		return getBindingPropertyAccess().getRule();
	}
	
	//enum BindinType returns BindingType:
	//	BooleanProperty | DoubleProperty | FloatProperty | IntegerProperty | ObservableList | ObjectProperty |
	//	StringProperty;
	public BindinTypeElements getBindinTypeAccess() {
		return eBindinType;
	}
	
	public EnumRule getBindinTypeRule() {
		return getBindinTypeAccess().getRule();
	}
	
	//ControlFX:
	//	TableViewFX;
	public ControlFXElements getControlFXAccess() {
		return pControlFX;
	}
	
	public ParserRule getControlFXRule() {
		return getControlFXAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//ModelFX:
	//	DerivedBean | Bean;
	public ModelFXElements getModelFXAccess() {
		return pModelFX;
	}
	
	public ParserRule getModelFXRule() {
		return getModelFXAccess().getRule();
	}
	
	//DerivedBean:
	//	{DerivedBean}
	//	'class' name=EString '{' ('instanceType:' instanceType=EString) (attributes+=AttributeFX attributes+=AttributeFX*)?
	//	'}';
	public DerivedBeanElements getDerivedBeanAccess() {
		return pDerivedBean;
	}
	
	public ParserRule getDerivedBeanRule() {
		return getDerivedBeanAccess().getRule();
	}
	
	//Bean:
	//	{Bean}
	//	'class' name=EString '{' (attributes+=AttributeFX attributes+=AttributeFX*)?
	//	'}';
	public BeanElements getBeanAccess() {
		return pBean;
	}
	
	public ParserRule getBeanRule() {
		return getBeanAccess().getRule();
	}
	
	//TableViewFX:
	//	{TableViewFX}
	//	'TableView' '{' ('name:' name=EString) ('usedModel:' usedModel=[ModelFX|EString])? ('usedFilter:'
	//	useFilter=EBoolean)? (columns+=TableColumnFX columns+=TableColumnFX*)?
	//	'}';
	public TableViewFXElements getTableViewFXAccess() {
		return pTableViewFX;
	}
	
	public ParserRule getTableViewFXRule() {
		return getTableViewFXAccess().getRule();
	}
	
	//TableColumnFX:
	//	{TableColumnFX}
	//	'Column'
	//	'(' ('name:' name=EString) ('width:' width=EInt)? ('attribute:' usedAttribute=[AttributeFX|EString])? ('useFilter:'
	//	useFilter=EBoolean)?
	//	')';
	public TableColumnFXElements getTableColumnFXAccess() {
		return pTableColumnFX;
	}
	
	public ParserRule getTableColumnFXRule() {
		return getTableColumnFXAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//AttributeFX:
	//	{AttributeFX} type=EString name=EString;
	public AttributeFXElements getAttributeFXAccess() {
		return pAttributeFX;
	}
	
	public ParserRule getAttributeFXRule() {
		return getAttributeFXAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
