/*
 * generated by Xtext 2.14.0
 */
package de.dc.emf.javafx.xtext.jvm.lang.parser.antlr;

import com.google.inject.Inject;
import de.dc.emf.javafx.xtext.jvm.lang.parser.antlr.internal.InternalJavaFXCuDslParser;
import de.dc.emf.javafx.xtext.jvm.lang.services.JavaFXCuDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class JavaFXCuDslParser extends AbstractAntlrParser {

	@Inject
	private JavaFXCuDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalJavaFXCuDslParser createParser(XtextTokenStream stream) {
		return new InternalJavaFXCuDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ProjectFX";
	}

	public JavaFXCuDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(JavaFXCuDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
