/*
 * generated by Xtext 2.14.0
 */
package de.dc.emf.javafx.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractJavaFXLangScopeProvider extends DelegatingScopeProvider {
}
