/**
 * generated by Xtext 2.17.0
 */
package de.dc.javafx.xcore.lang.edit.emfSupportDsl.impl;

import de.dc.javafx.xcore.lang.edit.emfSupportDsl.CopyContextMenu;
import de.dc.javafx.xcore.lang.edit.emfSupportDsl.EmfSupportDslPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Copy Context Menu</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CopyContextMenuImpl extends ContextMenuImpl implements CopyContextMenu
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CopyContextMenuImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EmfSupportDslPackage.Literals.COPY_CONTEXT_MENU;
  }

} //CopyContextMenuImpl
