/**
 * generated by Xtext 2.17.0
 */
package de.dc.javafx.xcore.lang.edit.emfSupportDsl.impl;

import de.dc.javafx.xcore.lang.edit.emfSupportDsl.EmfSupportDslPackage;
import de.dc.javafx.xcore.lang.edit.emfSupportDsl.TableViewFX;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Table View FX</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TableViewFXImpl extends SupportedControlImpl implements TableViewFX
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TableViewFXImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EmfSupportDslPackage.Literals.TABLE_VIEW_FX;
  }

} //TableViewFXImpl
