/**
 * generated by Xtext 2.17.0
 */
package de.dc.javafx.xcore.lang.edit.emfSupportDsl.impl;

import de.dc.javafx.xcore.lang.edit.emfSupportDsl.EmfSupportDslPackage;
import de.dc.javafx.xcore.lang.edit.emfSupportDsl.TreeViewFX;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Tree View FX</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TreeViewFXImpl extends SupportedControlImpl implements TreeViewFX
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TreeViewFXImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EmfSupportDslPackage.Literals.TREE_VIEW_FX;
  }

} //TreeViewFXImpl
