/**
 * generated by Xtext 2.17.0
 */
package de.dc.javafx.xcore.lang.edit.emfSupportDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Context Menu</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.dc.javafx.xcore.lang.edit.emfSupportDsl.EmfSupportDslPackage#getContextMenu()
 * @model
 * @generated
 */
public interface ContextMenu extends EObject
{
} // ContextMenu
