/**
 * generated by Xtext 2.17.0
 */
package de.dc.javafx.xcore.lang.edit.emfSupportDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List View FX</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.dc.javafx.xcore.lang.edit.emfSupportDsl.EmfSupportDslPackage#getListViewFX()
 * @model
 * @generated
 */
public interface ListViewFX extends SupportedControl
{
} // ListViewFX
