/**
 * generated by Xtext 2.17.0
 */
package de.dc.javafx.xcore.lang.edit.emfSupportDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.dc.javafx.xcore.lang.edit.emfSupportDsl.Model#getEcore <em>Ecore</em>}</li>
 * </ul>
 *
 * @see de.dc.javafx.xcore.lang.edit.emfSupportDsl.EmfSupportDslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Ecore</b></em>' containment reference list.
   * The list contents are of type {@link de.dc.javafx.xcore.lang.edit.emfSupportDsl.Ecore}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ecore</em>' containment reference list.
   * @see de.dc.javafx.xcore.lang.edit.emfSupportDsl.EmfSupportDslPackage#getModel_Ecore()
   * @model containment="true"
   * @generated
   */
  EList<Ecore> getEcore();

} // Model
