/*
 * generated by Xtext 2.14.0
 */
package de.dc.emf.javafx.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class JavaFXLangAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/dc/emf/javafx/xtext/parser/antlr/internal/InternalJavaFXLang.tokens");
	}
}
