<?xml version="1.0" encoding="ASCII"?>
<resource:RecentlyOpenFileHistory xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:resource="http://www.frateranatis.org/project">
  <files name="Test File" path="c:\text-file.txt"/>
  <files timestamp="2019-06-24T21:49:24.866" name="Example01.chart" path="C:\Users\Dim\Desktop\Emf-based-Files\Example01.chart"/>
</resource:RecentlyOpenFileHistory>
