<?xml version="1.0" encoding="ASCII"?>
<resource:RecentlyOpenFileHistory xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:resource="http://www.frateranatis.org/project">
  <files timestamp="2019-06-25T20:40:48.427" name="Example01.chart" path="C:\Users\Dim\Desktop\Emf-based-Files\Example01.chart"/>
  <files timestamp="2019-06-24T21:57:16.921" name="Example01.blog" path="C:\Users\Dim\Desktop\Emf-based-Files\Example01.blog"/>
  <files timestamp="2019-06-24T21:49:24.866" name="Example01.chart" path="C:\Users\Dim\Desktop\Emf-based-Files\Example01.chart"/>
  <files name="Test File" path="c:\text-file.txt"/>
  <files timestamp="2019-06-25T21:09:53.030" name="Example01.chart" path="C:\Users\Dim\Desktop\Emf-based-Files\Example01.chart"/>
</resource:RecentlyOpenFileHistory>
